FROM graphqlperl/mojoliciousplugin:latest

# Copy the current directory contents into the container
ADD . /app-prereq/

# Install any needed packages - -v so can see errors
RUN cd /app-prereq \
  && cpanm -v --installdeps . \
  && true
